[versions]
guava = "33.4.6-jre"
junit = "5.13.4"

[libraries]
guava                   = { module = "com.google.guava:guava", version.ref = "guava" }
junit_bom               = { module = "org.junit:junit-bom", version.ref = "junit" }
junit_platform_launcher = { module = "org.junit.platform:junit-platform-launcher" }
junit_vintage_engine    = { module = "org.junit.vintage:junit-vintage-engine" }
junit_jupiter_engine    = { module = "org.junit.jupiter:junit-jupiter-engine" }
junit_jupiter_api       = { module = "org.junit.jupiter:junit-jupiter-api" }
junit_jupiter           = { module = "org.junit.jupiter:junit-jupiter" }

[bundles]
junit_runtime           = [ "junit_platform_launcher", "junit_vintage_engine", "junit_jupiter_engine" ]
junit_jupiter           = [ "junit_jupiter", "junit_jupiter_api" ]
