name: Java Playwright CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - uses: actions/setup-node@v3
        with:
          node-version: 20

      - run: sudo apt-get update && sudo apt-get install -y \
          libgtk-4-1 libgraphene-1.0-0 libvpx9 libevent-2.1-7 libopus0 \
          gstreamer1.0-plugins-base gstreamer1.0-plugins-good \
          gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly \
          gstreamer1.0-libav gstreamer1.0-tools libharfbuzz-icu0 \
          libsecret-1-0 libhyphen0 libavif16

      - run: npm install -g playwright
      - run: npx playwright install firefox chromium webkit

      - run: chmod +x ./gradlew
      - run: ./gradlew clean build
