name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Install Playwright browsers
      run: ./gradlew playwrightInstall

    - name: Make gradlew executable
      run: chmod +x ./gradlew

    - name: Build and run tests
      run: ./gradlew clean build
